kind: pipeline
name: deploy

clone:
  skip_verify: true

steps:
- name: mirror
  image: alpine/git
  commands:
  - git push --mirror "https://$$LOGIN@github.com/aspriddell/Dragon6-Deploy.git"
  environment:
    LOGIN:
      from_secret: gitlogin
- name: dockerize
  image: plugins/docker
  settings:
    username: 
      from_secret: HEROKU_USR
    password:
      from_secret: HEROKU_KEY
    repo: registry.heroku.com/dragon6/web
    registry: registry.heroku.com
    dockerfile: Dragon6 Core/Dockerfile