kind: pipeline
name: deploy

clone:
  skip_verify: true

steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.1-stretch
  commands:
  - dotnet restore
  - dotnet build -c Release

- name: heroku
  image: ruby
  commands:
  - gem install dpl
  - dpl --provider=heroku --app=dragonsix --api-key=$KEY
  environment:
    KEY:
      from_secret: HEROKU_KEY
