kind: pipeline
name: stage

clone:
  skip_verify: true

steps:

- name: toheroku
  image: ruby
  commands:
  - gem install dpl
  - dpl --provider=heroku --app=dragonsix --api-key=$KEY
  environment:
    KEY:
      from_secret: HEROKU_KEY