kind: pipeline
name: deploy

clone:
  skip_verify: true

steps:
- name: dockerize
  image: plugins/docker
  settings:
    username: 
      from_secret: HEROKU_USR
    password:
      from_secret: HEROKU_KEY
    repo: registry.heroku.com/dragonsix/web
    registry: registry.heroku.com
    dockerfile: Dragon6 Core/Dockerfile