kind: pipeline
name: deploy

clone:
  skip_verify: true

steps:
- name: mirror
  image: alpine/git
  commands:
  - git push --mirror "https://$$LOGIN@github.com/dragonfruitnetwork/Dragon6-API.git"
  environment:
    LOGIN:
      from_secret: gitlogin
  when:
    branch:
    - dev

- name: dockerize-heroku
  image: plugins/docker
  settings:
    username: 
      from_secret: HEROKU_USR
    password:
      from_secret: HEROKU_KEY
    repo: registry.heroku.com/dragonsix/web
    registry: registry.heroku.com
    dockerfile: Dragon6 Core/Dockerfile-heroku
  when:
    branch:
    - heroku-prod