language: csharp
mono: none
dotnet: 2.2.203
include:
    - os: linux
      dist: bionic
script:
 - dotnet restore
 - dotnet build
 - cd "Dragon6-Test/bin/Debug/netcoreapp2.2"
 - dotnet run Dragon6-Test.dll